In [ ]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


Ans to the Q1

In [ ]:
a1=np.array(ages)
a2=np.array(salaries)
print(a1)
print(a2)
print(a1.dtype)
print(a2.dtype)
print(a1.ndim)
print(a2.ndim)
print(a1.shape)
print(a2.shape)
print(a1.size)
print(a2.size)



[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
int64
1
1
(10,)
(10,)
10
10


Ans to the Q2:

In [ ]:
x=np.max(a2)
print(x)
y=np.min(a2)
print(y)

aa2=np.mean(a2)
print(aa2)
aa1=np.mean(a1)
print(aa1)

89735
30769
57446.9
38.5


Ans to the Q(3)

In [ ]:
v=a1[a1>30]
print(v)
print(v.size)

[56 46 32 38 56 36 40]
7


Ans to the Q(4)

In [ ]:
ans=np.array(a1+5) # ans=a1+5
# print(a1)
print(ans)

[61 51 37 30 43 61 41 45 33 33]


Ans to the Q(5)

In [ ]:
ex=np.sum(a2)

print(ex)
print(np.max(a2)-np.min(a2)) # x-y


574469
58966


ANs to the Q(6)

In [ ]:
f=pd.read_csv('employees.csv')
df=pd.DataFrame(f)
print(df.head(5))
print()
print(df.info())
print()
print(df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


Ans to the Q(7)


In [ ]:
x=df[['id','age','salary']]
print(x)
print()
print(x.tail(3))


   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


Ans to the Q(8)

In [ ]:
y=df[df['dept']=='IT']
print(y)
print()
print(y.shape[0])

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

3


Ans to the Q(9)

In [ ]:
ans2=df.sort_values(['salary'],ascending=False)
print(ans2[['age','dept']].head(3))

   age     dept
6   36  Finance
7   40       IT
0   56       HR

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR


Ans to the Q(10)

In [ ]:

df.loc[df['salary']>80000,'salary']=80000 # ekhane direct df ke replace korte hobe naki copy ke eita bole dewa ucit cilo...bcz eta direct df ke change kori fele

print(df)
print()
print(df['salary'].mean())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR

55863.3
